### ISSUE TITLE
part Generating Poisoned Data

### ISSUE THREAD

**Issue by LeoStrange26** [nishadsinghi/CleanCLIP#1]
in part Generating Poisoned Data，
maybe you can give an example but not just the template

**Comment by nishadsinghi** [comment]
Hey! An example would look something like this:

`python -m backdoor.create_backdoor_data --train_data /work/nsinghi/GCC_Training/train.csv --templates data/ImageNet1K/validation/classes.py --num_backdoor 1000 --label banana --patch_type random --patch_location random --size_train_data 500000`
