### ISSUE TITLE
The generated file is missing some image paths

### ISSUE THREAD

**Issue by tongzhang111** [nishadsinghi/CleanCLIP#5]
I found that some data did not have corresponding paths in the generated corresponding files(train.csv).

<img width="860" alt="WeChat97b749e6c8386f54dc1370edf0487d7f" src="https://github.com/nishadsinghi/CleanCLIP/assets/104766709/a42d6006-5326-4471-b14c-3d39927f2b93">

**Comment by nishadsinghi** [comment]
Hey, @tongzhang111! Thanks for your interest in our work. The behaviour you described is a bit surprising and I'm not sure why this happened. Could you please count the number of rows in the .csv file where a valid path is present? Also, what is the number of files inside the `images` folder? if the number is in the ballpark of 3M in both cases, then you probably don't need to worry. In this case, I would just modify `train.csv` to remove the rows that don't have a path in the first column. But, if there are a lot of paths missing, then we might have to investigate further.

**Comment by tongzhang111** [comment]
I am very grateful for your reply. Can you compress the data you obtained and release a link. Can I obtain training data through your link?

**Comment by nishadsinghi** [comment]
The data is really big (it usually takes 2-3 days to download) so I don't think it is practically possible for me to host it somewhere. Were you able to check how many files were downloaded?

**Comment by tongzhang111** [comment]
I found out before that there were indeed a relatively small number of images. I think it may be due to network issues. I will try downloading the data again today

**Comment by nishadsinghi** [comment]
Yes, that is what I would have also suggested. Please feel free to comment again if needed :) Also, in case it wasn't clear, here is how you can download the dataset:

1. wget https://storage.cloud.google.com/gcc-data/Train/GCC-training.tsv?_ga=2.191230122.-1896153081.1529438250
2. Run download.py -f GCC-training.tsv -d <directory where images should be stored>

**Comment by wenxian-ok** [comment]
> 我之前发现图片数量确实比较少，我觉得可能是网络问题，今天再试试下载数据

Hello, do you have the fully downloaded CC3M dataset? I am also encountering this issue where most of the `image` paths in the `train.csv` file are empty.
