### ISSUE TITLE
Some confusion about the command

### ISSUE THREAD

**Issue by tongzhang111** [nishadsinghi/CleanCLIP#7]
I'm not quite sure which file validation_data refers to. Can you modify the readme file to make the content clearer?

![image](https://github.com/nishadsinghi/CleanCLIP/assets/104766709/05379c45-d889-4c7d-8893-e21eb025d0f4)

**Comment by nishadsinghi** [comment]
Hey,

The validation file is /data/ImageNet1K/validation/labels.csv

Let me know if this works :)

**Comment by jsrdcht** [comment]
> Hey,
> 
> The validation file is /data/ImageNet1K/validation/labels.csv
> 
> Let me know if this works :)

Good job! Stars for u😄

**Comment by 2022wannarest** [comment]
I execute it during training
python -m src.main --name exp4 --train_data utils/images/backdoor_dog_random_random_16_34537_5000.csv --validation_data utils/images/backdoor_dog_random_random_16_34537_5000.csv --image_key image --caption_key caption --device_ids 0

Executed when eval
python -m src.main --name cifar10 --eval_data_type CIFAR10 --eval_test_data_dir data/CIFAR10/test/ --device_id 0 --checkpoint logs/exp4/checkpoints/best.pt

But the Clean Accuracy and ASR values ​​I got are the same, and both are a bit low. Where did I go wrong?

![image](https://github.com/user-attachments/assets/34f4db86-5183-4c79-a1f0-d07eb5f76b68)
