### ISSUE TITLE
About training CLIP with CC3M data

### ISSUE THREAD

**Issue by Seung-B** [nishadsinghi/CleanCLIP#8]
Hello,

I would like to train the CLIP model from scratch on CC3M data. However, if I try to create and use the dataloader, the process ends as the RAM usage increases significantly. Maybe it's because the data is large, have you experienced any similar problems?

**Comment by nishadsinghi** [comment]
Hey @Seung-B, thanks for your interest in our work! We did not encounter this issue. Have you tried reducing the batch-size?

**Comment by Seung-B** [comment]
Thanks for your response!
CC3M data cannot be fully downloaded now, so I am using the data in the hugging face(2.95M).
There are many links where CC3M data has expired, so I can get only 2.2M data.
Do you know where I can get full data?

**Comment by Seung-B** [comment]
Thank you for responding to my question!
I used the Hugging Face dataset, and even if it takes a long time, I obtained 2.95M cc3m data by saving them locally one by one.

https://huggingface.co/datasets/pixparse/cc3m-wds
